services:
    mafiascum.topicMaker.listener:
        class: mafiascum\isos\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@dbal.conn'
        tags:
            - { name: event.listener }