services:
    mafiascum.topicMaker.listener:
        class: mafiascum\topicMaker\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@dbal.conn'
            - '@user'
            - '@language'
            - '@auth'
        tags:
            - { name: event.listener }
    mafiascum.topicMaker.controller:
    class: mafiascum\isos\controller\main_listener
    arguments:
        - '@config'
        - '@controller.helper'
        - '@language'
        - '@template'
        - '@dbal.conn'
        - '@user'
        - '@request'